### PR TITLE
Lecture10

### PR DESCRIPTION
**Pull request by CoderPat**
Add lecture 10 notes.

### CODE REVIEW

**Comment by CoderPat** [comment]
This branch isn't fully ready to be merged.
For some reason, pdflatex isn't including the new chapter in the table of contents. If someone who has had this problem before could shed some light on this issue would appreciate it to avoid having to search online for it.

**Comment by DimaSamoz** [comment]
The problem might be the `\end{document}` in the end of lecture10.tex :)

**Comment by CoderPat** [comment]
That was it, my bad from copy-pasting from overleaf. Thanks
Should ready for merge then,

**Comment by technicalguy** [comment]
Hopefully Marcelo will review it soon :)

**Pull request merged**
